### PR TITLE
Issue159 create registerform

### LINKED ISSUE #159: Frontend registerform for application
Create a possiblity to register to our application in frontend. Use the backend mutation for inserting a user to database.

### PR DESCRIPTION
**Pull request by att78**
closes #159 

## Creates registerform:
- includes material-ui package for react
-  form validation with yup and formik. Yup is in separated file.
- uses register-mutation to add new user to database
- also handles success and error situations.
- hint for code evaluation: database.md includes sufficient guide for checking the content of database.

### CODE REVIEW

**Review by guotin — APPROVED** [review]
Seems to add the correct stuff to database and informs of duplicate errors. Maybe one future improvement could be that the confirm password field informs something like `"Passwords do not match"`.

**Review by ilkkamaksy — APPROVED** [review]
lgtm

**Comment by jakekall** [comment]
The form itself looks great but a few nitpicks about the validation:
- The form says that "Make sure your password includes no spaces" but if a space is anywhere else other than the end of the password, it's accepted.
-  The max password length is pretty low. 
- The form doesn't actually tell the user which special characters are needed. For example if the only special character in your password is a "€" it won't accept but if you have "!" and "€" then it will accept.

**Comment by ilkkamaksy** [comment]
Would be a good idea to add tests for all those cases jake mentioned.

**Pull request merged**
