### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by guotin**
* @tulma95 suggested that fast guide to start development should be found in README
* Improved the definition of done based on our discussions. Feel free to change if I missed something tell me what you think about it.
* Some changes to backend documentation. Feel free to change them aswell if you have any other suggestions.

### CODE REVIEW

**Comment by att78** [comment]
Should we have  also a link for the staging server in documentation? Currently we rely on remembering the right port for the staging server.

**Comment by guotin** [comment]
I don't know and I don't really have a strong opinion on this. You can add it anywhere you wish, if you want. Is it something that is of interest to someone else viewing this repository? The staging stuff is documented in our drive already for us team members.

**Comment by att78** [comment]
Oh, I forgot about the drive. I do not have a strong opinion either. The question just occurred to my mind.. forgot to approve the changes last time.

**Review by att78 — APPROVED** [review]

**Review by ilkkamaksy — APPROVED** [review]
LGTM

**Pull request merged**
